/**
 * Dashboard Augmentation - Utility Modules
 * ========================================
 * 
 * Initializes market ticker, weather & moon phase, news headlines, and persistent scratchpad.
 */

/* Ensure DOM elements exist and integrate with script.js output */
function ensureElements() {
	// Check and create container structure
	if (!document.getElementById('main-container')) {
		const container = document.createElement('div');
		container.id = 'main-container';
		document.body.insertBefore(container, document.body.firstChild);
	}

	const mainContainer = document.getElementById('main-container');

	// Ensure upper area exists
	if (!document.getElementById('upper-area')) {
		const upperArea = document.createElement('div');
		upperArea.id = 'upper-area';
		mainContainer.insertBefore(upperArea, mainContainer.firstChild);
	}

	const upperArea = document.getElementById('upper-area');

	// Ensure main panel exists
	if (!document.getElementById('main-panel')) {
		const mainPanel = document.createElement('div');
		mainPanel.id = 'main-panel';
		upperArea.appendChild(mainPanel);
	}

	// Ensure weather widget exists
	if (!document.getElementById('weather-widget')) {
		const weatherWidget = document.createElement('div');
		weatherWidget.id = 'weather-widget';
		weatherWidget.className = 'utility-panel';
		weatherWidget.innerHTML = '<h2>Weather & Moon</h2><div id="weather-content"></div>';
		document.getElementById('main-panel').appendChild(weatherWidget);
	}

	// Ensure right sidebar exists
	if (!document.getElementById('right-sidebar')) {
		const rightSidebar = document.createElement('div');
		rightSidebar.id = 'right-sidebar';
		upperArea.appendChild(rightSidebar);
	}

	const rightSidebar = document.getElementById('right-sidebar');

	// Ensure search boxes container exists
	if (!document.getElementById('search-boxes')) {
		const searchBoxes = document.createElement('div');
		searchBoxes.id = 'search-boxes';
		rightSidebar.insertBefore(searchBoxes, rightSidebar.firstChild);
	}

	// Ensure news widget exists
	if (!document.getElementById('news-widget')) {
		const newsWidget = document.createElement('div');
		newsWidget.id = 'news-widget';
		newsWidget.className = 'utility-panel';
		newsWidget.innerHTML = '<h2>News</h2><ul id="news-list"></ul>';
		rightSidebar.appendChild(newsWidget);
	}

	// Ensure market ticker exists
	if (!document.getElementById('market-ticker')) {
		const ticker = document.createElement('div');
		ticker.id = 'market-ticker';
		ticker.className = 'ticker-panel';
		const tickerH2 = document.createElement('h2');
		tickerH2.textContent = 'Stocks';
		ticker.appendChild(tickerH2);
		rightSidebar.appendChild(ticker);
	}

	// Ensure scratchpad widget exists
	if (!document.getElementById('scratchpad-widget')) {
		const scratchpadWidget = document.createElement('div');
		scratchpadWidget.id = 'scratchpad-widget';
		scratchpadWidget.className = 'utility-panel';
		scratchpadWidget.innerHTML = `
			<h2>Scratchpad</h2>
			<textarea id="scratchpad-input" placeholder="Quick notes..."></textarea>
			<button id="scratchpad-copy">Copy</button>
		`;
		rightSidebar.appendChild(scratchpadWidget);
	}

	// Ensure bookmark columns container exists
	if (!document.getElementById('bookmark-columns')) {
		const bookmarkColumns = document.createElement('div');
		bookmarkColumns.id = 'bookmark-columns';
		mainContainer.appendChild(bookmarkColumns);
	}

	// Ensure game overlay exists
	if (!document.getElementById('game-overlay')) {
		const overlay = document.createElement('div');
		overlay.id = 'game-overlay';
		const canvas = document.createElement('canvas');
		canvas.id = 'breakout-canvas';
		canvas.width = 480;
		canvas.height = 320;
		overlay.appendChild(canvas);
		document.body.appendChild(overlay);
	}

	// Ensure easter-egg-trigger exists
	if (!document.getElementById('easter-egg-trigger')) {
		const trigger = document.createElement('div');
		trigger.id = 'easter-egg-trigger';
		trigger.setAttribute('aria-hidden', 'true');
		document.body.appendChild(trigger);
	}
}

/* Reorganize script.js output: move bookmark blocks to bookmark-columns container */
function reorganizeBookmarks() {
	const bookmarkColumns = document.getElementById('bookmark-columns');
	if (!bookmarkColumns) return;

	// Move all .block elements (generated by script.js) to bookmark-columns
	const blocks = document.querySelectorAll('body > .block');
	blocks.forEach(block => {
		bookmarkColumns.appendChild(block);
	});

	// Move all #searches form elements to search-boxes container
	const searchBoxes = document.getElementById('search-boxes');
	if (searchBoxes) {
		const searches = document.getElementById('searches');
		if (searches) {
			const forms = searches.querySelectorAll('form');
			// Only keep Google and Wikipedia
			forms.forEach((form, index) => {
				// Keep first 2 (Google and Images), skip to Wikipedia (index 3)
				if (index === 0 || index === 3) {
					searchBoxes.appendChild(form.cloneNode(true));
				}
			});
			searches.remove();
		}
	}

	// Move clock to footer area if needed
	const clock = document.getElementById('clock');
	if (clock && !document.getElementById('main-container').contains(clock)) {
		// Clock will stay where it is (absolute positioning)
	}
}

/* Vanguard Market Ticker */
function initTicker() {
	const symbols = ['VOO', 'VTI', 'VOX', 'VCR', 'VDC', 'VDE', 'VFH', 'VHT', 'VIS', 'VGT', 'VAW', 'VNQ', 'VPU'];
	const tickerContainer = document.getElementById('market-ticker');
	
	if (!tickerContainer) return;

	// Find or create ticker items container
	let itemsContainer = tickerContainer.querySelector('.ticker-items');
	if (!itemsContainer) {
		itemsContainer = document.createElement('div');
		itemsContainer.className = 'ticker-items';
		
		for (const symbol of symbols) {
			const item = document.createElement('div');
			item.className = 'ticker-item';
			item.innerHTML = `
				<span class="ticker-symbol">${symbol}</span>
				<span class="ticker-price">--</span>
				<span class="ticker-change">--</span>
			`;
			itemsContainer.appendChild(item);
		}
		
		tickerContainer.appendChild(itemsContainer);
	}
}

/* Weather & Moon Phase */
function initWeather() {
	const weatherWidget = document.getElementById('weather-content');
	
	if (!weatherWidget) return;
	
	weatherWidget.innerHTML = '<div style="color: #666; font-size: 11px;">Loading weather...</div>';
	
	const latitude = 41.6528;
	const longitude = -83.5379;
	const url = `https://api.open-meteo.com/v1/forecast?latitude=${latitude}&longitude=${longitude}&current=temperature_2m,weather_code&daily=weather_code,temperature_2m_max,temperature_2m_min,precipitation_probability_max&temperature_unit=fahrenheit&timezone=America%2FNew_York`;
	
	fetch(url)
		.then(response => response.json())
		.then(data => {
			const current = data.current;
			const daily = data.daily;
			
			// Map WMO weather codes to conditions
			const weatherCodeMap = {
				0: 'Clear', 1: 'Mostly Clear', 2: 'Partly Cloudy', 3: 'Cloudy',
				45: 'Foggy', 48: 'Foggy', 51: 'Light Drizzle', 53: 'Drizzle', 55: 'Heavy Drizzle',
				61: 'Slight Rain', 63: 'Rain', 65: 'Heavy Rain', 71: 'Slight Snow', 73: 'Snow',
				75: 'Heavy Snow', 77: 'Snow Grains', 80: 'Rain Showers', 81: 'Heavy Showers',
				82: 'Violent Showers', 85: 'Snow Showers', 86: 'Heavy Snow Showers', 95: 'Thunderstorm'
			};
			
			const getCondition = (code) => weatherCodeMap[code] || 'Unknown';
			
			// Calculate moon phase
			const moonPhase = calculateMoonPhase();
			
			let html = `
				<div class="weather-section">
					<span class="weather-label">Now:</span>
					<span>${Math.round(current.temperature_2m)}°F, ${getCondition(current.weather_code)}</span>
				</div>
				<div class="weather-section">
					<span class="weather-label">Today:</span>
					<span>${Math.round(daily.temperature_2m_max[0])}°/${Math.round(daily.temperature_2m_min[0])}° | ${daily.precipitation_probability_max[0]}% rain</span>
				</div>
				<div class="weather-section">
					<span class="weather-label">Tomorrow:</span>
					<span>${Math.round(daily.temperature_2m_max[1])}°/${Math.round(daily.temperature_2m_min[1])}° | ${daily.precipitation_probability_max[1]}% rain</span>
				</div>
				<div class="weather-section">
					<span class="weather-label">Moon:</span>
					<span>${moonPhase}</span>
				</div>
			`;
			
			weatherWidget.innerHTML = html;
		})
		.catch(error => {
			console.log('Weather data unavailable:', error);
			weatherWidget.innerHTML = `
				<div class="weather-section">
					<span class="weather-label">Weather:</span>
					<span>Unavailable</span>
				</div>
			`;
		});
}

/* Calculate Moon Phase */
function calculateMoonPhase() {
	const moonPhases = [
		'🌑 New Moon', '🌒 Waxing Crescent', '🌓 First Quarter',
		'🌔 Waxing Gibbous', '🌕 Full Moon', '🌖 Waning Gibbous',
		'🌗 Last Quarter', '🌘 Waning Crescent'
	];
	
	const now = new Date();
	const epoch = new Date('2000-01-06T18:14:00Z');
	const daysElapsed = (now - epoch) / (1000 * 60 * 60 * 24);
	const dayInCycle = daysElapsed % 29.53058867;
	const phaseIndex = Math.floor((dayInCycle / 29.53058867) * 8) % 8;
	
	return moonPhases[phaseIndex];
}

/* Top 3 News Headlines - IMPROVED PARSER */
function initNews() {
	const newsList = document.getElementById('news-list');
	
	if (!newsList) return;
	
	newsList.innerHTML = '<li style="color: #666; font-size: 11px;">Loading headlines...</li>';
	
	// Google News RSS - most reliable and direct
	const rssUrl = 'https://news.google.com/rss?hl=en-US&gl=US&ceid=US:en';
	const apiUrl = `https://api.rss2json.com/v1/api.json?rss_url=${encodeURIComponent(rssUrl)}&count=3`;
	
	fetch(apiUrl, {
		method: 'GET',
		headers: {
			'Accept': 'application/json'
		}
	})
		.then(response => {
			if (!response.ok) throw new Error(`HTTP error! status: ${response.status}`);
			return response.json();
		})
		.then(data => {
			console.log('News API Response:', data);
			
			if (!data.items || data.items.length === 0) {
				newsList.innerHTML = '<li style="color: #666; font-size: 11px;">No headlines available</li>';
				return;
			}

			let html = '';
			let validCount = 0;
			
			for (let i = 0; i < data.items.length && validCount < 3; i++) {
				const item = data.items[i];
				
				// Extract title and link from various possible formats
				let title = item.title || item.description || '';
				let link = item.link || item.url || item.guid || '';
				
				// Clean up title
				if (title) {
					title = title
						.replace(/[\s-]+AP[\s-]*$/i, '')
						.replace(/[\s-]+BBC[\s-]*$/i, '')
						.replace(/[\s-]+Reuters[\s-]*$/i, '')
						.replace(/^[\s-]*/, '');
				}
				
				if (title && title.trim() && link) {
					html += `<li><a href="${link}" target="_blank" rel="noopener noreferrer">${title}</a></li>`;
					validCount++;
				}
			}
			
			if (html) {
				newsList.innerHTML = html;
			} else {
				newsList.innerHTML = '<li style="color: #666; font-size: 11px;">No valid headlines found</li>';
			}
		})
		.catch(error => {
			console.log('News fetch error:', error);
			newsList.innerHTML = '<li style="color: #666; font-size: 11px;">Headlines unavailable</li>';
		});
}

/* Persistent Scratchpad */
function initScratchpad() {
	const textarea = document.getElementById('scratchpad-input');
	const copyBtn = document.getElementById('scratchpad-copy');
	
	if (!textarea) return;
	
	// Load from localStorage
	const saved = localStorage.getItem('dash_scratchpad');
	if (saved) {
		textarea.value = saved;
	}
	
	// Save on input
	textarea.addEventListener('input', function() {
		localStorage.setItem('dash_scratchpad', this.value);
	});
	
	// Copy button
	if (copyBtn) {
		copyBtn.addEventListener('click', async function() {
			try {
				await navigator.clipboard.writeText(textarea.value);
				const originalText = copyBtn.textContent;
				copyBtn.textContent = 'Copied!';
				setTimeout(() => {
					copyBtn.textContent = originalText;
				}, 2000);
			} catch (error) {
				console.log('Copy failed:', error);
				alert('Failed to copy to clipboard');
			}
		});
	}
}

/* Initialize all modules when DOM is ready */
document.addEventListener('DOMContentLoaded', function() {
	ensureElements();
	
	// Wait for script.js to finish building the page
	setTimeout(() => {
		reorganizeBookmarks();
		initTicker();
		initWeather();
		initNews();
		initScratchpad();
	}, 50);
});
